const imageFiles={"carteira": "2 - carteira.png", "relatorios": "3 - relatórios.png", "analises": "5 - análises.png", "simulador": "6 - simulador.png", "mercado": "4 - mercado.png", "perfil": "7 - perfil.png", "configuracoes": "8 - configurações.png"};
const modules={
carteira:{title:'Como está minha carteira?',description:'Acompanhe posições, preço médio, dividendos e distribuição por ativo. Veja o Score consolidado e o rendimento sobre o valor investido.',points:['Posição e preço médio','Score da carteira','Distribuição por ativo']},
relatorios:{title:'Como planejar o próximo aporte?',description:'Informe o valor disponível e consulte a matriz de aporte. Leia os diagnósticos de concentração e a comparação com indicadores macroeconômicos.',points:['Matriz de aporte','Diagnóstico de concentração','Comparação com CDI, Selic e IPCA']},
analises:{title:'O que muda de um fundo para outro?',description:'Coloque dois fundos lado a lado. Compare fundamentos, histórico de proventos e correlação de preços para aprofundar sua avaliação.',points:['Comparação de fundamentos','Histórico de dividendos','Correlação entre fundos']},
simulador:{title:'E se a carteira fosse diferente?',description:'Filtre os fundos e monte uma composição hipotética. Observe os indicadores e a exposição da simulação antes de tomar uma decisão.',points:['Filtros por segmento e Score','Carteira hipotética','Análise da composição']},
mercado:{title:'Sua gestão começa no registro.',description:'Lance compras e vendas pela boleta. Acompanhe o preço médio, o registro da última operação e as notícias relacionadas à carteira.',points:['Boletas de compra e venda','Registro da última operação','Radar de notícias']},
perfil:{title:'Onde você está. Aonde quer chegar.',description:'Relacione sua capacidade de aporte à meta de renda. Acompanhe as projeções, o calendário de dividendos e a capacidade de reinvestimento.',points:['Projeção de metas','Calendário de dividendos','Efeito bola de neve']},
configuracoes:{title:'Entenda e cuide do seu sistema.',description:'Consulte a metodologia, acompanhe o status das atualizações e transfira seus registros entre versões pelo painel de importação e exportação.',points:['Metodologia do Score','Status de atualização','Importação e exportação']}
};
const tabs=[...document.querySelectorAll('[role=tab]')], reduced=matchMedia('(prefers-reduced-motion: reduce)');
function animateImage(img){img.classList.remove('image-enter');if(!reduced.matches){void img.offsetWidth;img.classList.add('image-enter')}}
function activate(button){const key=button.dataset.module,item=modules[key];tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===button));t.tabIndex=t===button?0:-1});document.getElementById('painel').setAttribute('aria-labelledby',button.id);document.getElementById('panel-title').textContent=item.title;document.getElementById('panel-description').textContent=item.description;document.getElementById('module-points').replaceChildren(...item.points.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));const img=document.getElementById('screen');img.src='assets/images/'+imageFiles[key];img.alt='Interface Alpha FIIs: '+button.textContent.trim();animateImage(img);document.getElementById('screen-link').href=img.src;document.getElementById('screen-link').setAttribute('aria-label','Ampliar '+button.textContent.trim())}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>activate(t));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();activate(tabs[n]);tabs[n].focus()}})});
document.querySelectorAll('[data-hero]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-hero]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const img=document.getElementById('hero-screen');img.src='assets/images/'+imageFiles[button.dataset.hero];img.alt='Tela completa do Alpha FIIs: '+button.textContent;animateImage(img)}));
const dialog=document.getElementById('image-viewer'),viewerImage=document.getElementById('viewer-image'),viewerBody=document.querySelector('.viewer-body'),zoomButton=document.getElementById('zoom-image');let returnFocus;
function openViewer(img){returnFocus=document.activeElement;viewerImage.src=img.src;viewerImage.alt=img.alt;document.getElementById('viewer-title').textContent=img.alt;viewerBody.classList.remove('zoomed');zoomButton.setAttribute('aria-pressed','false');zoomButton.textContent='Zoom 100%';dialog.showModal();document.body.classList.add('modal-open')}
document.querySelector('.hero-image-button').addEventListener('click',()=>openViewer(document.getElementById('hero-screen')));document.getElementById('screen-link').addEventListener('click',e=>{e.preventDefault();openViewer(document.getElementById('screen'))});document.getElementById('close-viewer').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');returnFocus?.focus()});zoomButton.addEventListener('click',()=>{const zoomed=viewerBody.classList.toggle('zoomed');zoomButton.setAttribute('aria-pressed',String(zoomed));zoomButton.textContent=zoomed?'Ajustar à tela':'Zoom 100%'});
if('IntersectionObserver' in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-head,.showcase,.method-grid,.routine,.creator,.access-grid,.faq').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}
const progress=document.createElement('div');progress.className='page-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);let scheduled=false;function updateProgress(){const total=document.documentElement.scrollHeight-innerHeight;progress.style.transform='scaleX('+(total>0?scrollY/total:0)+')';scheduled=false}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateProgress)}},{passive:true});updateProgress();
activate(tabs[0]);
